services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8081:8080'
      - '7071:7071'
    volumes:
      - ./conf/core-site.xml:/etc/trino/etc/hadoop/core-site.xml
      - ./conf/metastore-site.xml:/etc/trino/metastore-site.xml
      - ./etc/catalog:/etc/trino/catalog
      - ./etc/jvm.config:/etc/trino/jvm.config
      - ./monitoring/jmx/jmx_prometheus_javaagent-0.20.0.jar:/opt/jmx/jmx_prometheus_javaagent.jar:ro
      - ./monitoring/jmx/trino-jmx-config.yaml:/opt/jmx/trino-jmx-config.yaml:ro

    networks:
      - trino-network

    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: trino.logs

  postgres:
    image: 'postgres:11'
    hostname: postgres
    expose:
      - '5432'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hive_db
    networks:
      - trino-network
    volumes:
      - hive_pgdata:/var/lib/postgresql/data
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: postgres.logs

  postgres-data:
    image: 'postgres:11'
    hostname: postgres-data
    container_name: postgres-data
    expose:
      - '5432'
    ports:
      - '5433:5432'  # Different external port to avoid clash
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: data_db
    volumes:
      - ./csv-upload:/csv
      - data_pgdata:/var/lib/postgresql/data
    networks:
      - trino-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: postgres.data.logs

  hive-metastore:
    image: 'my-hive-metastore:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083'   # Metastore Thrift
      - '7070:7070'   # JMX Exporter port
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
      - ./conf/core-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/core-site.xml:ro
      - ./monitoring/jmx/jmx_prometheus_javaagent-0.20.0.jar:/opt/jmx/jmx_prometheus_javaagent.jar:ro
      - ./monitoring/jmx/hive-jmx-config.yaml:/opt/jmx/hive-jmx-config.yaml:ro
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres
      JAVA_TOOL_OPTIONS: >
        -javaagent:/opt/jmx/jmx_prometheus_javaagent.jar=7070:/opt/jmx/hive-jmx-config.yaml
    depends_on:
      - postgres
    networks:
      - trino-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: hive.logs

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      
    command: server --console-address ":9001" /data
    networks:
      - trino-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: minio.logs


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - trino-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: prometheus.logs

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - trino-network
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: grafana.logs

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin@postgres:5432/hive_db?sslmode=disable"
    ports:
      - '9187:9187'
    depends_on:
      - postgres
    networks:
      - trino-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: postgres.exporter.logs

  postgres-data-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:admin123@postgres-data:5432/data_db?sslmode=disable"
    ports:
      - '9188:9187'
    depends_on:
      - postgres-data
    networks:
      - trino-network

    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: postgres.data.exporter.logs

volumes:
  minio-data:
    driver: local
  grafana-storage:
    driver: local
  hive_pgdata:
    driver: local
  data_pgdata:
    driver: local

networks:
  trino-network:
    external: true