
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3-amd64
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - trino-network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.3-amd64
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - trino-network


  fluentd:
    image: fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - trino-network
    depends_on:
      - elasticsearch


networks:
  trino-network:
    external: true

volumes:
  esdata: