groups:
  - name: example
    rules:
      - alert: TrinoDown
        expr: up{job="trino"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Trino is down"
          description: "Trino instance is not responding for more than 1 minute."