global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'trino'
    static_configs:
      - targets: ['trino-coordinator:7071']

  - job_name: 'hive'
    static_configs:
      - targets: ['hive-metastore:7070']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'postgres-data'
    static_configs:
      - targets: ['postgres-data-exporter:9187']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
