
# File & Table Info
CSV_FILE = "data/sales_data_sample.csv"
TABLE_NAME = "sales_data"
PARQUET_FILE = f"{TABLE_NAME}.parquet"

# PostgreSQL Config
PG_USER = "admin"
PG_PASSWORD = "admin123"
PG_HOST = "postgres-data"
PG_PORT = "5432"
PG_DB = "data_db"
PG_SCHEMA = "sales"

# MinIO Config
MINIO_ENDPOINT = "http://minio:9000"
MINIO_ACCESS_KEY = "minio"
MINIO_SECRET_KEY = "minio123"
MINIO_BUCKET = "datalake"
S3_KEY = f"{PG_SCHEMA}/{TABLE_NAME}/{PARQUET_FILE}"
S3_LOCATION = f"s3a://{MINIO_BUCKET}/{PG_SCHEMA}/{TABLE_NAME}/"

# Trino Config
TRINO_HOST = "trino-coordinator"
TRINO_PORT = 8080
TRINO_CATALOG = "hive"
TRINO_SCHEMA = PG_SCHEMA
TRINO_USER = "admin"

# Hive Table Columns (update as needed)
HIVE_COLUMNS = """
    ORDERNUMBER INT,
    QUANTITY INT,
    PRICEEACH DOUBLE,
    ORDERLINENUMBER INT,
    SALES DOUBLE,
    ORDERDATE VARCHAR,
    STATUS VARCHAR,
    OTR_ID VARCHAR,
    MONTH_ID INT,
    YEAR_ID INT,
    PRODUCTLINE VARCHAR,
    MSRP INT,
    PRODUCTCODE VARCHAR,
    CUSTOMERNAME VARCHAR,
    PHONE VARCHAR,
    ADDRESSLINE1 VARCHAR,
    ADDRESSLINE2 VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    POSTALCODE VARCHAR,
    COUNTRY VARCHAR,
    TERRITORY VARCHAR,
    CONTACTLASTNAME VARCHAR,
    CONTACTFIRSTNAME VARCHAR,
    DEALSIZE VARCHAR
"""
